spring.application.name=provider-service
server.port=8082
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

kafka.bootstrap.servers=kafka-EB:9092
camel.springboot.main-run-controller=true

hawtio.authenticationEnabled=false
